@host=http://localhost:5128

### Register user
POST {{host}}/api/auth/register
Content-Type: application/json

{
    "name": "Cyril",
    "email": "cyril@morozov.com",
    "password": "Cyril123"
}

### Login user
POST {{host}}/api/auth/login
Content-Type: application/json

{
    "email": "cyril@morozov.com",
    "password": "Cyril123"
}